[project]
name = "experiment-kicad-purge"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
license = "MIT"
dependencies = [
    "kicad-tools>=0.10.2",
    "requests>=2.32.5",
]

[project.scripts]
kicad_purge = "kicad_purge.main:main"
